evolution-gaming/kafka-flow

- core/src/main/scala/com/evolutiongaming/kafka/flow/KeyFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/KeyStateOf.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/RecordFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/Tick.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/TickOption.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/TickToState.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/KeyFlowSpec.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/PartitionFlowSpec.scala
- version.sbt
It is requried to allow one to reuse Timer and FoldToState functionality easily without having to copy-paste KeyFlow or RecordFlow code.
> Introduce a transitionary structure called Tick.

- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/CassandraSnapshots.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSchema.scala
This is required to avoid growing number of stored snapshots forever for long living entities. The change is backwards compatible and deployment without a downtime is supported.
> Store only one snapshot per key

- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
Avoid the need to define the codec twice, i.e. like this:
implicit val journalCodec = JsonCodec.default[Try]
implicit val journalParser = JournalParser.of[F]
implicit val stateCodec = JsonCodec.default[F]
CassandraPersistence.withSchema[F, State](...)
> Avoid the need to define the codec twice

- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlowOf.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/PartitionFlowSpec.scala
- persistence-kafka/src/it/scala/com/evolutiongaming/kafka/flow/StatefulProcessingWithKafkaSpec.scala
- persistence-kafka/src/main/scala/com/evolutiongaming/kafka/flow/kafkapersistence/package.scala
Micro-PoC that this filtering code works:
```scala
import cats.data.NonEmptyList
import cats.effect.IO
import cats.instances.all._
import cats.syntax.all._
import scala.collection.SortedMap
import scala.concurrent.ExecutionContext
implicit val cs = IO.contextShift(ExecutionContext.global)
val filterFun = (x: Int) => IO(x != 1)
val map1 =
SortedMap("key1" -> NonEmptyList.of(1, 2, 3), "key2" -> NonEmptyList.of(1, 1, 1))
val map2 =
SortedMap("key1" -> NonEmptyList.of(1, 1, 1))
val map3 =
SortedMap("key1" -> NonEmptyList.of(1, 2, 3))
def filter(map: SortedMap[String, NonEmptyList[Int]]): List[(String, NonEmptyList[Int])] =
map.toList
.parTraverseFilter { case (key, records) =>
records.toList.filterA(filterFun).map(filtered => NonEmptyList.fromList(filtered).map(nel => (key, nel)))
} …
```
> Add filtering capabilities to PartitionFlow

- build.sbt
- core/src/main/scala/com/evolutiongaming/kafka/flow/FoldOption.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/persistence/PersistenceOf.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/KafkaSnapshot.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/timer/Timestamps.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraConfig.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraModule.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/ConsistencyOverrides.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/StatementHelper.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/CassandraJournals.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/CassandraKeys.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/CassandraSnapshots.scala
- project/build.properties
- version.sbt
Currently there is not way to tune consistency level for read/write queries in cassandra-persistence as that level that is provided in `CassandraConfig.client` will be applied for both. My case is to increase consistency level for writes to EACH_QUORUM which will cause a huge performance penalty for reads.
Suggested fix 
- take ConsistencyConfig from kafka-journal
- add new factory method CassandraPersistence.withSchema(session, sync, consistencyConfig) which does the same as `withSchema(session, sync)` but also adds `setConsistencyLevel` on the level of `PreparedStatement` construction.
- move `PreparedStatement` construction to a separate companion as the queries to be referenced from 2 places.
Sample usage on the application side
```
evolutiongaming.appname.cassandra { …
```
> Add read write config support for cassandra persistence

- core/src/main/scala/com/evolutiongaming/kafka/flow/AdditionalStatePersist.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/AdditionalStatePersistOf.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/FoldToState.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/KeyFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/KeyFlowOf.scala
Motivation: we disable `ProducerLogging` when we tolerate and ignore persistence failures so it doesn't log records that failed to be produced on `ERROR` level as such errors are supposed to be expected.  
However, if `ProducerLogging` is disabled, there's no way to find out what the state was when it failed to be persisted additionally. This PR addresses it.
> Log state on additional state persist failure

- core/src/main/scala/com/evolutiongaming/kafka/flow/AdditionalStatePersist.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/AdditionalStatePersistOf.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/FoldToState.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/KeyFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/KeyFlowOf.scala
Motivation: we disable `ProducerLogging` when we tolerate and ignore persistence failures so it doesn't log records that failed to be produced on `ERROR` level as such errors are supposed to be expected.  
However, if `ProducerLogging` is disabled, there's no way to find out what the state was when it failed to be persisted additionally. This PR addresses it.
> Log state on additional state persist failure (cats-effect 2)

- build.sbt
- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/TopicFlow.scala
- persistence-kafka/src/it/resources/logback-test.xml
- project/Dependencies.scala
Please note that as of version 2.10.0 cats-helper doesn't have a dependency on logback. Thus, kafka-flow also doesn't force it now either (using only SLF4J API) and it has to be added manually via using cats-helper-logback library or any other way of adding logback.
> Update cats-helper, smetrics, scache, kafka-journal [CE2]

- core/src/main/scala/com/evolutiongaming/kafka/flow/KafkaKey.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/LogPrefix.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotDatabase.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/Snapshots.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotsOf.scala
- persistence-kafka/src/main/scala/com/evolutiongaming/kafka/flow/kafkapersistence/KafkaPersistenceModule.scala
- persistence-kafka/src/main/scala/com/evolutiongaming/kafka/flow/kafkapersistence/KafkaSnapshotWriteDatabase.scala
- minor refactorings
- ensure that persistence-related log messages (`"deleted snapshot"`) are logged with a prefix (format: `"<topic>-<partition> <key>"`)
> Improve logging for Kafka-based persistence

- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlowConfig.scala
Currently, the parallel recovery doesn't limit the number of fibers it creates when recovering the state, meaning that for each recovered key a fiber is spawned.
Source: https://github.com/evolution-gaming/kafka-flow/blob/46072b4d23e76962bb0858db86d8339d82e8633e/core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlow.scala#L128-L130
This can lead to CPU exhaustion when there are too many keys and for each one a fiber is spawned, attempting to recover snapshots and consuming all CPU resources, whether it's for scheduling reasons or actual work of querying the storage.
> Add option to bound parallelism for snapshot recovery [CE2]

- .github/workflows/ci.yml
- .github/workflows/dependency-graph.yml
- use https://github.com/scalacenter/sbt-dependency-submission/ to submit the graph of dependencies (one can see it in  `Insights` - `Dependency graph`)
- polish `ci.yml` a bit:
- update actions' versions
- switch from `setup-scala` to `setup-java` and use Java 17 instead of 11
- enable `Report test coverage`, `Publish documentation / Deploy` and `Slack notification` only in the main repository (don't trigger in forks)
> Submit dependency graph to GitHub

- docs/persistence.md
- metrics/src/main/scala/com/evolutiongaming/kafka/flow/compression/CompressorMetrics.scala
Remove _total suffix from compressor metrics, this is not allowed in Prometheus >=1.0.0
When scraping metrics with the old name, an error is returned:
```
java.lang.IllegalArgumentException: 'kafka_flow_compressor_compressed_bytes_total': Illegal metric name. The metric name must not include the '_total' suffix. Call PrometheusNaming.sanitizeMetricName(name) to avoid this error.
```
The new name is the same as the outcome of `PrometheusNaming.sanitizeMetricName("kafka_flow_compressor_compressed_bytes_total")`
> remove _total suffix from compressor metrics

- core/src/main/scala/com/evolutiongaming/kafka/flow/kafka/Codecs.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/kafka/KafkaModule.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/kafka/OffsetToCommit.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraCodecs.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/CassandraJournals.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/CassandraKeys.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/CassandraSnapshots.scala
- persistence-kafka/src/main/scala/com/evolutiongaming/kafka/flow/kafkapersistence/KafkaPartitionPersistence.scala
Drop dependency on `com.evolutiongaming.kafka.journal.util.SkafkaHelper`, introducing used codecs locally.  
Another step towards https://github.com/evolution-gaming/kafka-flow/issues/592
> Drop dependency on SkafkaHelper

- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/key/KeySchemaSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/KeySchema.scala
1. Add `scassandra`-based API to `KeySchema` to further drop `kafka-journal`-based one (https://github.com/evolution-gaming/kafka-flow/issues/592)
2. Add integration tests for `KeySchema` validating both old and new versions work as expected
> Cassandra KeySchema improvements

- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSchemaSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSchema.scala
1. Add `scassandra`-based API to `SnapshotSchema` to further drop `kafka-journal`-based one (https://github.com/evolution-gaming/kafka-flow/issues/592)
2. Add integration tests for `SnapshotSchema` validating both old and new versions work as expected
> Cassandra SnapshotSchema improvements

- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/CassandraSessionStub.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/journal/JournalSchemaSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/JournalSchema.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/KeySchema.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSchema.scala
1. Add `scassandra`-based API to `JournalSchema` to further drop `kafka-journal`-based one (https://github.com/evolution-gaming/kafka-flow/issues/592)
2. Add integration tests for `JournalSchema` validating both old and new versions work as expected
3. Improve `KeySchema` and `SnapshotSchema`: delegate to a `scassandra`-based implementation instead of having two identical ones
> Cassandra JournalSchema improvements

- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/CassandraKeys.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/KeySegments.scala
This is a step towards https://github.com/evolution-gaming/kafka-flow/issues/592. 
- remove methods that were marked for removal since long ago
- introduce our own version of `KeySegment` instead of `Segment` from `kafka-journal` and a corresponding set of methods
- make current methods delegate to the new ones
Current methods aren't deprecated yet because there's no alternative of `CassandraKeys`, `CassandraSnapshots`, `CassandraJournals`, `CassandraPersistence` that would use `CassandraSession` from `scassandra` instead of `kafka-journal` one. I plan to gradually introduce these and mark the old implementations as deprecated once all new ones are done. Until then, I will only introduce new APIs and change the old ones to delegate to them.
Next step is introducing our own `SegmentNr`
> introduce own KeySegments instead of kafka-journal Segments

- core/src/main/scala/com/evolutiongaming/kafka/flow/journal/JournalParser.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/registry/EntityRegistryTest.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/FlowSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/journal/JournalSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/key/KeySpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraCodecs.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraHealthCheckOf.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraModule.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/SessionHelper.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/CassandraJournals.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/CassandraKeys.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/migration/migration.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/CassandraSnapshots.scala
- project/Dependencies.scala
Changes:
1. `kafka-journal` updated to the latest
2. update `CassandraKeys`, `CassandraSnapshots`, `CassandraJournals` and `CassandraPersistence` to use `scassandra` APIs, mark old methods as deprecated
3. introduce some extension methods for `CassandraSession` (copied from `kafka-journal`) that will facilitate further migration of healthcheck-related pieces of code
**note**: this breaks binary compatibility of the aforementioned classes unfortunately as they now have to require `Async` instead of a bunch of other traits (tagless final is cool innit). hopefully no one will notice as it's unlikely to be embedded somewhere
> update CassandraKeys, CassandraSnapshots, CassandraJournals, CassandraPersistence to use scassandra APIs

- build.sbt
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/CassandraSessionStub.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/CassandraSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/FlowSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/journal/JournalSchemaSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/journal/JournalSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/key/KeySchemaSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/key/KeySpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSchemaSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSpec.scala
- persistence-cassandra/src/main/scala/com/evolution/kafka/flow/cassandra/CassandraHealthCheckOf.scala
- persistence-cassandra/src/main/scala/com/evolution/kafka/flow/cassandra/CassandraModule.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraHealthCheckOf.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/SessionHelper.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/JournalSchema.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/CassandraKeys.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/KeySchema.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/migration.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/CassandraSnapshots.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSchema.scala
- project/Dependencies.scala
this is a part of https://github.com/evolution-gaming/kafka-flow/issues/592
- introduce a new `CassandraModule` under a `com.evolution.kafka.flow.cassandra` package using `scassandra` API
- introduce a new `CassandraHealthCheckOf ` under a `com.evolution.kafka.flow.cassandra` package using `scassandra` API
- deprecate the old `CassandraModule` and `CassandraHealthCheckOf`
- deprecate old APIs of `JournalSchema`, `KeySchema`, `SnapshotSchema`
- provide `com.evolutiongaming.kafka.flow.migration` to facilitate migration of ToBytes/FromBytes
> introduce new CassandraModule

- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlowOf.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/RemapKey.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/PartitionFlowSpec.scala
- persistence-kafka-it-tests/src/test/resources/logback-test.xml
- persistence-kafka-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/RemapKeySpec.scala
- persistence-kafka/src/main/scala/com/evolutiongaming/kafka/flow/kafkapersistence/package.scala
Add the ability to derive and remap keys before handling records. The records are updated with the derived keys so that the downstream components (such as `FilterRecord` or `FoldOption`) will see the derived key in the `ConsumerRecord`.
> allow deriving and remapping keys

- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
- build.sbt
- project/build.properties
- project/plugins.sbt
- version.sbt
The current release process is cumbersome, requiring multiple manual steps in a strict sequence: first, updating the version in `version.sbt`, then manually creating a GitHub release with the same version, after which the release is triggered. This process can be simplified to improve efficiency and reduce potential errors.
This PR introduces a new model for publishing, triggered by pushing git tags in the `v*` format. When such a tag is pushed, the release process automatically starts.
The `version.sbt` file has been removed and replaced with [sbt-dynver](https://github.com/sbt/sbt-dynver), which dynamically sets the version property based on the latest git tag. This ensures that when a new `vX.Y.Z` tag is pushed, the version used during publishing step is correctly set, streamlining the …
> Introduce a custom GH action to publish a new release only on git tag

- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/KeySchema.scala
This fits the use case as `keys` table is read intensively during the bootstrap phase when eager recovery is used, and then it does a lot of updates/deletes which plays well with this strategy and allows avoiding putting more pressure on the compaction process. We've observed significant performance gains when using this strategy compared to the default one in a keyspace with hundreds of thousands of keys -- compaction manages to keep up and allows for a fast keys recovery
> Make keys DDL use LeveledCompactionStrategy by default

- core/src/main/scala/com/evolutiongaming/kafka/flow/kafka/KafkaModule.scala
Hi.
Looks like in KafkaModule we need to add SSL related settings to kafka healthcheck consumer config, similar like Producer config is being created.
Reference - https://github.com/evolution-gaming/kafka-flow/blob/master/core/src/main/scala/com/evolutiongaming/kafka/flow/kafka/KafkaModule.scala#L50
Currently without passing SSL related settings to consumer config, one might hit on exception (SSL handshake failed) if 'security-protocol' setting is set to "SSL".
> Pass SSL related settings to kafka healthcheck consumer

- core/src/main/scala/com/evolutiongaming/kafka/flow/key/KeyDatabase.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/key/Keys.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/key/KeysOf.scala
Currently, when deleting a key, the log message doesn't give much information, looking like this:
```
2025-01-21 11:45:14,543 INFO io-compute-0 c.e.k.f.k.KeyDatabase deleted key
```
This PR adds more info to the log message, prefixing it with topic-partition and key info, so it'll look like this:
```
2025-01-21 11:45:14,543 INFO io-compute-0 c.e.k.f.k.KeyDatabase [topic-1 key1] deleted key
```
> log topic-partition and key in KeyDatabase/Keys logging when deleting a key

- .github/workflows/ci.yml
- build.sbt
- core-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/ForAllKafkaSuite.scala
- core/src/main/scala-3/com/evolutiongaming/kafka/flow/persistence/compression/CodecOps.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/PartitionFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/TopicFlow.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/kafka/KafkaModule.scala
- core/src/main/scala/com/evolutiongaming/kafka/flow/persistence/compression/HeaderAndPayload.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/ConsumerFlowSpec.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/KeyFlowSpec.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/PartitionFlowSpec.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/registry/EntityRegistryTest.scala
- core/src/test/scala/com/evolutiongaming/kafka/flow/timer/TimerFlowOfSpec.scala
- metrics/src/main/scala/com/evolutiongaming/kafka/flow/FlowMetrics.scala
- metrics/src/test/scala/com/evolutiongaming/kafka/flow/FoldMetricsSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/CassandraSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
- persistence-kafka-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/ForAllKafkaSuite.scala
- persistence-kafka/src/main/scala/com/evolutiongaming/kafka/flow/kafkapersistence/KafkaPartitionPersistence.scala
- project/Dependencies.scala
Cross compile for Scala 3, except for the journal module, because there is no Scala 3 version of kafka-journal.
> Cross compile for Scala 3

- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/journal/JournalSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/key/KeySpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/CassandraPersistence.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/RecordExpiration.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/cassandra/StatementHelper.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/CassandraJournals.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/key/CassandraKeys.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/snapshot/CassandraSnapshots.scala
Adds TTL option to Cassandra tables, to let the data expire automatically.
Some work was done to clean up the constructors and factory methods and old methods were marked for removal. 
In certain places the deprecated annotation could not be used, because the old method is used instead of the one with default parameters.
> add ttls to cassandra persist statements

- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/CassandraSessionStub.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/FlowSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/journal/JournalSpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/key/KeySpec.scala
- persistence-cassandra-it-tests/src/test/scala/com/evolutiongaming/kafka/flow/snapshot/SnapshotSpec.scala
- persistence-cassandra/src/main/scala/com/evolutiongaming/kafka/flow/journal/CassandraJournals.scala
Same as https://github.com/evolution-gaming/kafka-flow/pull/736 but for `CassandraJournals`
> Prepare `CassandraJournals` statements only once at the startup
